services:
##============== MANDA ================##
  nginx:
    container_name: nginx               #container name       
    build: ./requirements/nginx         #path to Dockerfile
    networks:                           #network name
      - inception
    volumes:                            #volumes mapping  
      - wordpress:/var/www/html
    ports:                              #port mapping
      - "443:443"
    depends_on:                         #dependency on other services
      - wordpress
    restart: on-failure                 #restart policy  

  mariadb:
    container_name: mariadb         
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    healthcheck:                      # healthcheck configuration
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASS}"] #If MySQL responds with mysqld is alive, the container is marked healthy.
      interval: 5s                   # Docker checks health every 5 seconds.
      timeout: 5s                    # If the command doesn’t finish within 5 seconds → failure.  
      retries: 10                    #After 10 consecutive failures, the container becomes unhealthy.
      start_period: 30s              #Docker ignores failures during the first 30 seconds (gives MySQL time to boot).

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_started
    expose:
      - "9000"
    restart: on-failure

##============== BONUS ================##

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - inception
    restart: on-failure
    expose:
    - "6379"
    volumes:
    - redis:/var/lib/redis

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    networks:
    - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: on-failure

  static-site:
    container_name: static-site
    build: ./requirements/bonus/static-site
    networks:
      - inception
    ports:
      - "8081:80"
    restart: on-failure


  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure

  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "9001:9000"    
      - "9443:9443"
      - "8000:8000"
    restart: on-failure

##============== NETWORK ================##

networks:
  inception:
    name: inception 
    driver: bridge #network driver
  
##============== VOLUMES ================##

volumes:
  mariadb:
    name: mariadb
    driver: local                             #volume driver
    driver_opts:            #volume options 
      device: /home/adrouin/data/mariadb      #path on the host
      o: bind               #bind mount
      type: none            #no specific filesystem type
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/adrouin/data/wordpress
      o: bind
      type: none
  redis:
    name: redis
    driver: local
    driver_opts:
      device: /home/adrouin/data/redis
      o: bind
      type: none
  portainer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adrouin/data/portainer
